### PR TITLE
< Changes in dutch names (GLD,LB,ZH) >

### PR DESCRIPTION
**Pull request by javastraat**
thanx for all the work, more fixes coming soon :)

### CODE REVIEW

**Comment by PD1LOI** [comment]
Flevoland zou dan ook veranderd moeten worden van "FD" naar "FLD".


Op zo 1 jul. 2018 15:51 schreef Albert Einstein <notifications@github.com>:

**Comment by javastraat** [comment]
ja gezien komt eran is nog veel te doen om alles super mooi te krijgen
eng:
yeap seen it, alot todo to get it nice an shinny :)

**Comment by KD4Z** [comment]
Thanks for your tweaks @javastraat .    I'll take a deeper look in a few days, we have a national holiday this week and I'm headed where WiFi is scarce!  However, I don't want to change the displayed values for the UK and USA.  They are short for a reason. That allows more opportunity for the display code to display the city in a larger font more often.   We all know what USA and UK means....

**Comment by javastraat** [comment]
check i will revoke uk and usa
found afew more dutch thingies 🤗

Sent from my iPhonie
https://einstein.amsterdam


On 2 Jul 2018, at 23:28, KD4Z <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your tweaks @javastraat<https://github.com/javastraat> . I'll take a deeper look in a few days, we have a national holiday this week and I'm headed where WiFi is scarce! However, I don't want to change the displayed values for the UK and USA. They are short for a reason. That allows more opportunity for the display code to display the city in a larger font more often. We all know what USA and UK means....

**Comment by javastraat** [comment]
by the way my callsign is pd2emc

gr73

Sent from my iPhonie
https://einstein.amsterdam


On 3 Jul 2018, at 10:05, albert einstein <javastraat@hotmail.com<mailto:javastraat@hotmail.com>> wrote:

check i will revoke uk and usa
found afew more dutch thingies 🤗

Sent from my iPhonie
https://einstein.amsterdam


On 2 Jul 2018, at 23:28, KD4Z <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your tweaks @javastraat<https://github.com/javastraat> . I'll take a deeper look in a few days, we have a national holiday this week and I'm headed where WiFi is scarce! However, I don't want to change the displayed values for the UK and USA. They are short for a reason. That allows more opportunity for the display code to display the city in a larger font more often. We all know what USA and UK means....

**Comment by javastraat** [comment]
i meant changed not revoked *towarmhere*

**Comment by KD4Z** [comment]
By the way,  the abbreviations are intentionally shortened to be unique.   They may be similar to the real common use abbreviation, however what you are doing doesn't need to be done.  We never see these abbreviations as the radio re-expands them.  All you are doing is making the data file larger.  FD to FLD  You are adding a byte for each contact.   I don't want to do that.  If the expanded text is not culturally  correct, sure let us change it.  However, there are only so many characters than can be displayed on a line, and shortened expansion is often required.   My goal is to keep the contact file as small as possible.  The radio code will re-expand the abbreviated letters as coded.   Since I don't care if the data file is being used without my firmware, those users can't complain about the abbreviations if they are using firmware from other sources.

**Comment by javastraat** [comment]
in the database all FLevoland users have FLD, and in the display.c it says FL so you can delete fl,flevoland then because it will never be used or is the database incorrect ? just trying to fix them, so the same with N-B or N-Br or the software is incorrect or the database with all the users. easy fix is software instead of db

it's ok with me just rying to fix the display, i changed it for me and it works :)

**Pull request closed without merging**
